export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOAD_CHALLENGES = "LOAD_CHALLENGES";
export const GET_USER_CHALLENGES = "GET_USER_CHALLENGES";
export const ADD_USER_CHALLENGE = "ADD_USER_CHALLENGE";
export const DELETE_USER_CHALLENGE = "DELETE_USER_CHALLENGE";
export const SET_CHALLENGE_AS_COMPLETED = "SET_CHALLENGE_AS_COMPLETED";
export const UPDATE_PROFILE_PICTURE = "UPDATE_PROFILE_PICTURE";





